language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - mysql
# command to run tests
script: 
  - echo "skipping tests"
  #- pytest --cov=wikilink tests/integration --cov-report=html
branches:
 only:
  - dev
after_success:
  - coveralls
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true



